Django/TodoUserLogin/TodoUserLogin/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('basicapp/', include('basicapp.urls')),
]

Django/TodoUserLogin/basicapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from basicapp import views
from django.contrib.auth.views import LogoutView

app_name = 'basicapp'
urlpatterns = [
    path('create_task/', views.CreateTaskView.as_view(), name="create_task"),
    path('tasks_list/', views.TaskView.as_view(), name="task_list"),
    re_path('delete/(?P<pk>[0-9]+)$', views.DeleteTaskView.as_view(), name="delete_task"),
    re_path('update/(?P<pk>[0-9]+)$', views.UpdateTaskView.as_view(), name="update_task"),
    path('logout/', views.UserLogOut.as_view(), name='logout'),
    path('', views.UserLoginView.as_view(), name="login_view"),

]

Django/TodoUserLogin/basicapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class TodoApp(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.CharField(max_length=50)
    task_description = models.CharField(max_length=500)

    def __str__(self):
        return self.task

    def get_absolute_url(self):
        return reverse('basicapp:task_list')

Django/TodoUserLogin/basicapp/forms.py
from django import forms
from basicapp.models import TodoApp

class TasksForm(forms.ModelForm):
    class Meta:
        model = TodoApp
        fields = "__all__"

Django/TodoUserLogin/basicapp/views.py
from django.shortcuts import render
from basicapp import models
from django.http import HttpResponse
from basicapp.forms import TasksForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView

#Shiva
#hello@123

#skottala
#Welcome123

# Create your views here.
def index(request):
    return HttpResponse("<h1> Hi from the Index </h1>")

class UserLoginView(LoginView):
    fields = "__all__"
    template_name = "basicapp/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('basicapp:task_list')

class UserLogOut(LogoutView):
    template_name = "basicapp/logout.html"
    def get_success_url(self):
        return reverse_lazy('basicapp:login_view')

class MainMenu(TemplateView):
    template_name = "basicapp/base_page.html"

class TaskView(LoginRequiredMixin, ListView):
    model = models.TodoApp
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = context["tasks"].filter(user=self.request.user)
        return context

class CreateTaskView(CreateView):
    model = models.TodoApp
    fields = ("task", "task_description")
    # form = TodoAppForm()

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateTaskView, self).form_valid(form)

class DeleteTaskView(DeleteView):
    model = models.TodoApp
    success_url = reverse_lazy('basicapp:task_list')

class UpdateTaskView(LoginRequiredMixin,UpdateView):
    model = models.TodoApp
    fields = ("task", "task_description")

    def get_success_url(self):
        return reverse_lazy('basicapp:task_list')

Django/TodoUserLogin/basicapp/templates/basicapp/base_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to the basicapp page</h1>
  </body>
</html>

Django/TodoUserLogin/basicapp/templates/basicapp/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <h1>Login</h1>
      <form  method="post">
         {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Login">
      </form>
    </div>
    <p>Don't have any account ?</p>

  </body>
</html>

Django/TodoUserLogin/basicapp/templates/basicapp/logout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Logout Out</h1>
    <a href="{% url 'basicapp:login_view' %}">Login to View the task lists</a>

  </body>
</html>

Django/TodoUserLogin/basicapp/templates/basicapp/todoApp_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    {% for task in tasks %}
      <ul>
        <div class="">
           <h3>{{task.task }}</h3>
          <em>{{task.task_description }}</em>

          <a class="btn btn-warning" href="{% url 'basicapp:update_task' pk=task.pk %}">update</a>
          <a class="btn btn-danger" href="{% url 'basicapp:delete_task' pk=task.pk %}">delete</a>
        </div>
      </ul>
    {% endfor %}
    <div class="">
      <a href="{% url 'basicapp:create_task' %}">Create new Task</a>
    </div>

  </body>
</html>

Django/TodoUserLogin/basicapp/templates/basicapp/todoapp_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <h1>Confirm Delete</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" name="submit" value="submit">
      <a class="btn btn-success" href="{% url 'basicapp:task_list' %}">Cancel</a>
    </form>

  </body>
</html>

Django/TodoUserLogin/basicapp/templates/basicapp/todoapp_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    <h1>creating a new task</h1>

    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" name="submit" value="submit">
    </form>


  </body>
</html>