Django/crud/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name="basicapp"
urlpatterns = [
    url(r"^$", views.SchoolList.as_view(), name="school_list"),
    url(r"^(?P<pk>\d+)/$",views.SchoolDetailView.as_view(), name="detail"),
    url(r"^create/$",views.SchoolCreateView.as_view(), name="create"),
    url(r"update/(?P<pk>\d+)/$",views.SchoolUpdateView.as_view(), name="update"),
    url(r"delete/(?P<pk>\d+)/$",views.SchoolDeleteView.as_view(), name="delete"),
]

Django/crud/crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view(), name="index"),
    url(r'^basicapp/',include('basicapp.urls',namespace="basicapp")),
]

Django/crud/basicapp/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    principal = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basicapp:detail', kwargs={"pk":self.pk})

class Student(models.Model):
    name = models.CharField(max_length=250)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name="students", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Django/crud/basicapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from basicapp.models  import School, Student
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.
class IndexView(View):
    def get(self, request):
        return HttpResponse("<h1> hello World </h1>")

class TemplateEx(TemplateView):
    template_name = "basicapp/template.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["inject_data"] = "I am injected text"
        return context_data

class SchoolList(ListView):
    model = School
    template_name = "basicapp/school_list.html"

class SchoolDetailView(DetailView):
    model = School
    context_object_name = "school_details"

class SchoolCreateView(CreateView):
    model = School
    fields = ("name", "principal", "location")


class SchoolUpdateView(UpdateView):
    model = School
    fields = ("name", "principal")

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("basicapp:school_list")

Django/crud/basicapp/templates/basicapp/school_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> Confirm Delete {{school.name}}</h1>
    <form method="post">
      {% csrf_token %}
      <input type="Submit" name="" value="Delete">
    </form>
    <a href="{% url 'basicapp:detail' pk=school.pk %}">No</a>

  </body>
</html>

Django/crud/basicapp/templates/basicapp/school_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2> School Details are</h2>
      <h4>{{school_details.name}}</h4>
      <h4>{{school_details.location}}</h4>
      <h4>{{school_details.principal}}</h4>
      <p> list of Students are</p>
      {% for student in school_details.students.all %}
      <p> <b>{{ student.name }}</b> his age is <I>{{student.age}}</I></p>
      {% endfor %}

      <div class="">
        <a href="{% url 'basicapp:update' pk=school_details.pk %}">update School Detail</a>

      </div>
  </body>
</html>

Django/crud/basicapp/templates/basicapp/school_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% if not form.instance.pk %}
      Create School
    {% else %}
      Update School
    {% endif %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="Submit" name="" value="Submit">
    </form>
  </body>
</html>

Django/crud/basicapp/templates/basicapp/school_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ol>
      {% for school in school_list %}
      <h1><li><a href="{{school.id}}">{{school.name}}</a></li></h1>
      {% endfor %}
    </ol>

  </body>
</html>

Django/crud/basicapp/templates/basicapp/template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Hi From template View</h1>
    <h3>{{ inject_data }}</h3>
  </body>
</html>